import { TooltipProvider } from "@/components/ui/tooltip";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Suspense } from "react";
import { Toaster } from "sileo";
import "./globals.css";

const oxanium = localFont({
  src: "./fonts/Oxanium.ttf",
  style: "normal",
  variable: "--font-oxanium",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={oxanium.variable}>
      <body className={`${oxanium.variable} overflow-hidden antialiased`}>
        <Suspense>
          <Toaster
            position="top-center"
            options={{
              fill: "var(--color-cod-gray-900)",
              styles: {
                description: "text-muted-foreground",
              },
            }}
          />
          <TooltipProvider>{children}</TooltipProvider>
        </Suspense>
      </body>
    </html>
  );
}
